#!/bin/bash
# =============================================================================
# 3-generate_haproxy.sh — Generate haproxy.cfg from running containers
# Run this AFTER 2-start_containers.sh. Requires sudo.
#
# Usage:
#   sudo ./3-generate_haproxy.sh              # generate and reload
#   ./3-generate_haproxy.sh --dry-run         # preview only
#   sudo ./3-generate_haproxy.sh --only-up    # active VPN containers only
# =============================================================================

IMAGE="1proxy2xvpn"
HAPROXY_CFG="/etc/haproxy/haproxy.cfg"
OUTPUT_CFG="./haproxy.cfg"
FRONTEND_PORT="9999"
STATS_PORT="9998"
STATS_USER="haproxy"
STATS_PASS="ham123"
DRY_RUN=false
ONLY_UP=false
PROXY_CHECK_TIMEOUT=5

for ARG in "$@"; do
    case "${ARG}" in
        --dry-run)  DRY_RUN=true ;;
        --only-up)  ONLY_UP=true ;;
    esac
done

G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; N='\033[0m'
log()  { echo -e "${G}[haproxy-gen]${N} $*" >&2; }
warn() { echo -e "${Y}[haproxy-gen][WARN]${N} $*" >&2; }
die()  { echo -e "${R}[haproxy-gen][ERROR]${N} $*" >&2; exit 1; }

log "Collecting containers from image '${IMAGE}'..."
CONTAINERS=$(docker ps --filter "ancestor=${IMAGE}" --format "{{.Names}}")
TOTAL=$(echo "${CONTAINERS}" | grep -c . 2>/dev/null || echo 0)
[ "${TOTAL}" -eq 0 ] && die "No running containers found. Run ./2-start_containers.sh first."
log "Found: ${TOTAL} containers"

if [ "${ONLY_UP}" = true ]; then
    log "Mode --only-up: testing each container's VPN..."
    VERIFIED=""; COUNT_OK=0; COUNT_SKIP=0
    for NAME in ${CONTAINERS}; do
        PORT=$(docker inspect \
            --format='{{range $p,$b:=.NetworkSettings.Ports}}{{if eq $p "3128/tcp"}}{{(index $b 0).HostPort}}{{end}}{{end}}' \
            "${NAME}" 2>/dev/null)
        IP=$(curl -sf --max-time ${PROXY_CHECK_TIMEOUT} -x "http://localhost:${PORT}" "https://ifconfig.me" 2>/dev/null)
        if echo "${IP}" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
            VERIFIED="${VERIFIED} ${NAME}"; COUNT_OK=$((COUNT_OK+1))
        else
            warn "Skipping ${NAME}:${PORT} — VPN not responding"
            COUNT_SKIP=$((COUNT_SKIP+1))
        fi
    done
    CONTAINERS="${VERIFIED}"
    log "VPN active: ${COUNT_OK} | Skipped: ${COUNT_SKIP}"
fi

# Pre-collect ports (outside file writing block)
log "Collecting container ports..."
declare -A CONTAINER_PORTS
SKIPPED=0
for NAME in ${CONTAINERS}; do
    PORT=$(docker inspect \
        --format='{{range $p,$b:=.NetworkSettings.Ports}}{{if eq $p "3128/tcp"}}{{(index $b 0).HostPort}}{{end}}{{end}}' \
        "${NAME}" 2>/dev/null)
    if [ -n "${PORT}" ]; then
        CONTAINER_PORTS["${NAME}"]="${PORT}"
    else
        warn "Port not found for ${NAME} — skipping"
        SKIPPED=$((SKIPPED+1))
    fi
done
[ ${SKIPPED} -gt 0 ] && warn "${SKIPPED} container(s) skipped."

log "Generating ${OUTPUT_CFG}..."

cat > "${OUTPUT_CFG}" << HEADER
# =============================================================================
# haproxy.cfg — Auto-generated by 3-generate_haproxy.sh
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# Containers: ${#CONTAINER_PORTS[@]}
# =============================================================================

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    maxconn 50000

defaults
    log     global
    mode    tcp
    option  tcplog
    option  dontlognull
    option  redispatch
    retries 3
    timeout connect  10s
    timeout client   5m
    timeout server   5m
    timeout check    5s

frontend proxy_entrypoint
    bind *:${FRONTEND_PORT}
    default_backend vpn_proxies

backend vpn_proxies
    mode    tcp
    balance random
    option  redispatch
HEADER

for NAME in "${!CONTAINER_PORTS[@]}"; do
    PORT="${CONTAINER_PORTS[${NAME}]}"
    printf "    server %-45s 127.0.0.1:%-6s check inter 5s rise 2 fall 3\n" \
        "${NAME}" "${PORT}" >> "${OUTPUT_CFG}"
done

cat >> "${OUTPUT_CFG}" << FOOTER

listen stats
    bind *:${STATS_PORT}
    mode http
    stats enable
    stats uri /
    stats hide-version
    stats refresh 10s
    stats show-legends
    stats auth ${STATS_USER}:${STATS_PASS}
    stats admin if TRUE
FOOTER

log "Validating config..."
haproxy -c -f "${OUTPUT_CFG}"
[ $? -ne 0 ] && die "Invalid haproxy.cfg. Check output above."
log "Config valid. Servers: $(grep -c '^\s*server ' ${OUTPUT_CFG})"

if [ "${DRY_RUN}" = true ]; then
    warn "Dry-run mode: config not applied."
    echo ""; cat "${OUTPUT_CFG}"; echo ""; exit 0
fi

log "Applying to ${HAPROXY_CFG}..."
[ -f "${HAPROXY_CFG}" ] && cp "${HAPROXY_CFG}" "${HAPROXY_CFG}.bak" && log "Backup: ${HAPROXY_CFG}.bak"
cp "${OUTPUT_CFG}" "${HAPROXY_CFG}"

if systemctl reload haproxy 2>/dev/null; then
    log "HAProxy reloaded (zero downtime)."
elif systemctl restart haproxy 2>/dev/null; then
    log "HAProxy restarted."
else
    warn "Could not reload automatically. Run: sudo systemctl restart haproxy"
fi

echo ""
log "✓ Done!"
log "  Single proxy  : curl -x http://localhost:3100 https://ifconfig.me"
log "  Load balancer : curl -x http://localhost:${FRONTEND_PORT} https://ifconfig.me"
log "  Stats panel   : http://localhost:${STATS_PORT}  (${STATS_USER}:${STATS_PASS})"
log ""
log "Next step → run: ./4-status_proxies.sh"
