#!/bin/bash
# =============================================================================
# 12_proxychains.sh — Generate a ready-to-use proxychains.conf from running
# containers, mirroring what the `haproxy` command does for HAProxy.
#
# Each container's SOCKS5 port is added to the [ProxyList]. The file uses
# random_chain + chain_len=1, so proxychains picks ONE random proxy per
# connection — giving you the same per-connection IP rotation as the HAProxy
# round-robin endpoint, but usable with tools that only speak SOCKS5 through
# proxychains (e.g. nmap, hydra).
#
# Usage:
#   ./1proxy2xvpn proxychains            # write ./proxychains.conf
#   ./1proxy2xvpn proxychains --install  # also copy to /etc/proxychains4.conf
#                                          (backs up the existing one)
#
# Then run any tool through it:
#   proxychains4 -f proxychains.conf nmap -sT -Pn -p 80,443 target.com
#   proxychains4 -f proxychains.conf hydra -L users.txt -P pass.txt target ...
# =============================================================================
set -e

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
# shellcheck source=lib_common.sh
. "${PROJECT_ROOT}/scripts/lib_common.sh"

require_docker
print_banner

INSTALL=false
for ARG in "$@"; do
    case "${ARG}" in
        --install) INSTALL=true ;;
    esac
done

OUTPUT_CFG="${PROJECT_ROOT}/proxychains.conf"
SYSTEM_CFG="/etc/proxychains4.conf"

# ── Collect running containers and their SOCKS5 ports ─────────────────────────
section "Discovery"
mapfile -t CONTAINERS < <(list_containers)
TOTAL=${#CONTAINERS[@]}
[ "${TOTAL}" -eq 0 ] && die "No running containers. Run: ./1proxy2xvpn up"
log "Found ${TOTAL} containers"

declare -A SOCKS_PORTS
for NAME in "${CONTAINERS[@]}"; do
    SOCKS=$(container_socks_port "${NAME}")
    [ -n "${SOCKS}" ] && SOCKS_PORTS["${NAME}"]="${SOCKS}"
done

COUNT=${#SOCKS_PORTS[@]}
if [ "${COUNT}" -eq 0 ]; then
    error "None of the running containers expose a SOCKS5 port."
    error "SOCKS5 is opt-in. Recreate the containers with it enabled:"
    error "    ./1proxy2xvpn destroy"
    error "    ENABLE_SOCKS5=true ./1proxy2xvpn up"
    die "No SOCKS5 proxies available to write."
fi
ok "${COUNT} SOCKS5 proxies discovered"

# ── Generate proxychains.conf ─────────────────────────────────────────────────
section "Generating proxychains.conf"
{
    echo "# ============================================================================="
    echo "# proxychains.conf — auto-generated by 1proxy2Xvpn on $(date -u '+%Y-%m-%d %H:%M:%S') UTC"
    echo "# ${COUNT} SOCKS5 proxies. Do not edit by hand — regenerate with:"
    echo "#   ./1proxy2xvpn proxychains"
    echo "# ============================================================================="
    echo ""
    echo "# random_chain + chain_len=1 => pick ONE random proxy per connection."
    echo "# This reproduces the round-robin IP rotation of the HAProxy endpoint."
    echo "random_chain"
    echo "chain_len = 1"
    echo ""
    echo "# Resolve DNS through the proxy (prevents DNS leaks)."
    echo "proxy_dns"
    echo "remote_dns_subnet 224"
    echo ""
    echo "# Timeouts (milliseconds)."
    echo "tcp_read_time_out 15000"
    echo "tcp_connect_time_out 8000"
    echo ""
    echo "[ProxyList]"
    # Sort by port for a stable, readable file.
    for NAME in "${!SOCKS_PORTS[@]}"; do
        printf '%s %s\n' "${SOCKS_PORTS[$NAME]}" "${NAME}"
    done | sort -n | while read -r PORT NAME; do
        printf 'socks5 127.0.0.1 %-6s # %s\n' "${PORT}" "${NAME}"
    done
} > "${OUTPUT_CFG}"

ok "Wrote ${OUTPUT_CFG} (${COUNT} proxies)"

# ── Optionally install system-wide ────────────────────────────────────────────
if [ "${INSTALL}" = "true" ]; then
    if [ "$(id -u)" -ne 0 ]; then
        die "--install needs root. Run: sudo ./1proxy2xvpn proxychains --install"
    fi
    if [ -f "${SYSTEM_CFG}" ] && [ ! -f "${SYSTEM_CFG}.bak" ]; then
        cp "${SYSTEM_CFG}" "${SYSTEM_CFG}.bak"
        ok "Backed up existing config to ${SYSTEM_CFG}.bak"
    fi
    cp "${OUTPUT_CFG}" "${SYSTEM_CFG}"
    ok "Installed to ${SYSTEM_CFG}"
fi

# ── Usage hint ────────────────────────────────────────────────────────────────
section "Ready"
if ! command -v proxychains4 >/dev/null 2>&1 && ! command -v proxychains >/dev/null 2>&1; then
    warn "proxychains isn't installed yet. Install it with:"
    warn "    sudo apt-get install proxychains4"
    echo
fi
log "Use it with any tool:"
if [ "${INSTALL}" = "true" ]; then
    echo "  proxychains4 nmap -sT -Pn -p 80,443 target.com"
    echo "  proxychains4 hydra -L users.txt -P pass.txt target.com http-post-form ..."
else
    echo "  proxychains4 -f ${OUTPUT_CFG} nmap -sT -Pn -p 80,443 target.com"
    echo "  proxychains4 -f ${OUTPUT_CFG} hydra -L users.txt -P pass.txt target.com ..."
    echo
    log "Tip: install it system-wide so you can drop the -f flag:"
    echo "  sudo ./1proxy2xvpn proxychains --install"
fi
